server:
  port: 16050

spring:
  datasource:
    # url: jdbc:mysql://192.168.100.107:3306/midend_appointment?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&connectTimeout=60000&socketTimeout=60000&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    # username: admin
    # password: Abc_123456
    url: jdbc:mysql://127.0.0.1:3306/midend_appointment?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&connectTimeout=60000&socketTimeout=60000&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initial-size: 1
    min-idle: 1
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-While-Idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: false
    filters: stat,wall,log4j,config

mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  config: classpath:log4j2.xml

file:
  # 服务器资源文件存放路径 根据实际情况修改
  uploadDir: D:/Program Files (x86)/Apache Software Foundation/Tomcat 7.0/webapps/antdlib/
  # 服务器资源访问路径
  url: http://localhost:8080/antdlib/

config:
  # 生成号源天数
  scheduleDay: 10
  # 生成号源天数
  sourceDay: 7
  # 解锁号源分钟
  cancelMinutes: 3
  
# HIS 的一些基本配置
his-config:
  # HIS 接口地址
  request-url: http://192.168.101.57:8089/founderWebs/service/interface.do
  
# 短信平台配置
msg-config:
  # 短信接口地址
  request-url: http://192.168.103.107/SendMsg/tSmsNotify
  
#源启外联平台配置
yq-config:
  # 接口地址
  request-url: http://192.168.101.125:18401/orgine/powerrsp/service/overt