# Server settings
server:
  port: 18050

app:
  version: 1.0.0

# SPRING PROFILES
spring:
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
    multipart:
      maxFileSize : 1024MB
      maxRequestSize : 1024MB

  datasource:
#    url: jdbc:mysql://127.0.0.1:12233/midend_appointment?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&connectTimeout=60000&socketTimeout=60000&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
#    username: root
#    password: Admin@86970000
    # password: Geit@86#97$0000
    #    password: Abc_123456
    url: jdbc:mysql://192.168.103.107:6609/midend_appointment?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&connectTimeout=60000&socketTimeout=60000&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: admin
    password: Abc_123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initial-size: 1
    min-idle: 1
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-While-Idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j,config


mybatis:
  mapperLocations: classpath:mapper/*/*.xml
  configLocation: classpath:mybatis/mybatis-config.xml
logging:
  config: classpath:log4j2.xml

# HIS 的一些基本配置
his-config:
  # HIS 接口地址
  request-url: http://192.168.101.57:8089/founderWebs/service/interface.do
